version: "3.9"
#OVERRIDE ENV WITH SECRETS AT DEPLOY STAGE
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - './src:/app'
    working_dir: /app
    ports:
      - '8008:8008'

